config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :name, presence: true, length: {maximum: 255}, uniqueness: true
	validates :server_name, presence: true, uniqueness: true
	validates :executable_path, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	#require 'resque_scheduler'
	require 'resque/server'
	def index
		@task = Task.all
	end

	def show
		@task = Task.find(params[:id])
	end

	def new
		@task = Task.new
	end

	def create
		@task = Task.new(param_task)
		if @task.save
			#set delayed job
			#Resque.enqueue_at(@task.start_time,Test,@task.id)
			#set Dynamic scheduler
			# name = 'mailsmail'
			# config = {}
			# config[:class] = 'Album'
			# config[:args] = 'PO'
			# config[:every] = ['1h', {first_in: 2.minutes}]
			# config[:persist] = true
			#Resque.set_schedule(name, config)
			
			#convert_cron_time(@task)
			# Resque.set_schedule(@task.name, {
			#   :cron => "/1 * * * *",	
			#   :class => 'CreateQueue',
			#   :queue => @task.server_name,
			#   :message => 'notification message'      
			# })
			

			redirect_to tasks_path
		else
			render :new
		end 
	end

	def edit
		@task = Task.find(params[:id])
	end
	
	def update
		@task = Task.find(params[:id])
		if @task.update_attributes(param_task)
			Resque.set_schedule(@task.name, {
			  :cron => "/1 * * * *",	
			  :class => 'CreateQueue',
			  :queue => @task.server_name,
			  :message => 'notification message'      
			})
	  	redirect_to tasks_path
	  else
	  	render :edit
	  end
	end	

	def destroy
		@task = Task.find(params[:id])
		Resque.remove_schedule(@task.server_name)
		@task.destroy
		redirect_to tasks_path
	end

	# def convert_cron_time task
	# 	yr 	 =  @task.start_date.strftime("%Y").to_i
	# 	mnth =  @task.start_date.strftime("%m").to_i
	# 	date = @task.start_date.strftime("%d").to_i
	# 	hr =   @task.start_time.strftime("%I").to_i
	# 	min = @task.start_time.strftime("%M").to_i
	# 	hr = hr + 12 if @task.start_time.strftime("%p") == "PM"
	#   cron = 0 + " " + min + " " + date + " " + mnth + " " + "?" + " " + yr
	# end
	private
		def param_task
			params.require(:task).permit(:name, :start_date, :start_time, :end_date, :end_time, :server_name, :executable_path)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<body class="nav-md">
    <div class="container body">
      <div class="main_container">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>

</body>
</html>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => {:class => "form-horizontal center"}  do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>	
  <% end %>

    <div class="form-group">   
  		<%= f.label :name, "Task:", class: "col-md-4 control-label" %>
  	  <div class="col-md-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group" data-behaviour='datepicker'>   
      <%= f.label :start_date, "Start Date:", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :start_date, :id => 'datepicker', :readonly => true, :autocomplete => "on", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">   
      <%= f.label :start_time, "Start Time:", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.time_select :start_time, {:ampm => true}, :required => true,class: "form-control" %>
      </div>
    </div>

    <div class="form-group" data-behaviour='datepicker'>   
      <%= f.label :end_date, "End Date:", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :end_date, :id => 'datepicker1', :readonly => true, :autocomplete => "on", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">   
      <%= f.label :end_time, "End Time:", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%=f.time_select :end_time, {:ampm => true}, :required => true,class: "form-control" %>
      </div>
    </div>

	

    <div class="form-group">   
      <%= f.label :server_name, "Server Name:", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :server_name, class: "form-control" %>
      </div>
    </div> 
    
    <div class="form-group">   
      <%= f.label :executable_path, "Executable Path:", class: "col-md-4 control-label" %>
      <div class="col-md-4">
        <%= f.text_field :executable_path, class: "form-control" %>
      </div>
    </div> 

  	<div class="form-group">
     <div class= "col-md-4 control-label" %></div>
      <div class="col-md-4"> 
  		<%= f.submit 'Create', class: "save btn btn-success"  %>
      <%= link_to 'Back', tasks_path, class: "save btn btn-success" %>  
      </div>
  	</div>

<% end %>

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script type="text/javascript">

 
  $(function() {
    $("#datepicker").datepicker({
      format: "yyyy/mm/dd",
        changeYear: true,
        minDate: '+0D',

    });
    $("#datepicker1").datepicker({
      format: "yyyy/mm/dd",
        changeYear: true,
        minDate: '+0D'
    });
  });
  </script>

  <style type="text/css">
  .ui-datepicker {
  	background-color: white
  }
  </style>

app/views/tasks/edit.html.erb
<br><br>
<h1>Edit Task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedul Task</h1>
</br>
<!-- <table id="task_list" class="table table-bordered"> -->

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>server_name</th>
      <th>executable_path</th>
      <!-- <th>Section</th> -->
      <th>Edit</th>
      <th>SHow</th>
      <th>delete</th>
    </tr>
  </thead>
  <% unless @task.blank? %>
    <tbody>
       <% @task.each do |task|%>
        <tr>
          <td><%= task.name %></td>
          <td><%= task.server_name %></td>
          <td><%= task.executable_path %></td>
          <!-- <td><%#= assignment.section %></td> -->
          <td><%= link_to 'Show', task_path(task), class: "save btn btn-success" %></td>
          <td><%= link_to 'Edit', edit_task_path(task), class: "save btn btn-success" %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "save btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    no task found
  <% end %>
</table>

<br>

<%= link_to 'New task', new_task_path, class: "save btn btn-success" %>

app/views/tasks/new.html.erb
<br><br>
<div class="col-md-12" style="float: right">	
<h1>New Task</h1>
</div><br>
</br>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>start_date:</strong>
  <%= @task.start_date.strftime("%Y-%m-%d") rescue nil%>
</p>

<p>
  <strong>start_time:</strong>
  <%= @task.start_time.strftime("%H:%M") rescue nil%>
</p>

<p>
  <strong>end_date:</strong>
  <%= @task.end_date.strftime("%Y-%m-%d") rescue nil%>
</p>

<p>
  <strong>end_time:</strong>
  <%= @task.end_time.strftime("%H:%M") rescue nil%>
</p>

<p>
  <strong>server_name:</strong>
  <%= @task.server_name %>
</p>
<p>
  <strong>executable_path:</strong>
  <%= @task.executable_path %>
</p>
<!-- <p>
  <strong>Section:</strong>
  <%#= @task.section.name if @task.section %>
</p> -->

<%= link_to 'Edit', edit_task_path(@task), class: "save btn btn-success" %> |
<%= link_to 'Back', tasks_path, class: "save btn btn-success" %>